### ISSUE TITLE
为什么我生成不了

### ISSUE THREAD

**Issue by kennx** [HeskeyBaozi/hexo-generator-to-json#2]
- hexo: 3.7.1
- hexo-cli: 1.1.0
- os: Windows_NT 10.0.16299 win32 x64
- http_parser: 2.7.0
- node: 8.9.4
- v8: 6.1.534.50
- uv: 1.15.0
- zlib: 1.2.11
- ares: 1.10.1-DEV
- modules: 57
- nghttp2: 1.25.0
- openssl: 1.0.2n
- icu: 59.1
- unicode: 9.0
- cldr: 31.0.1
- tz: 2017b

`INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.generatePages (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\hexo-generator-to-json\dist\lib\generator.js:58:30)
    at Hexo.<anonymous> (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\hexo-generator-to-json\dist\index.js:43:50)
    at Hexo.tryCatcher (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.map.key (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\hexo\lib\hexo\index.js:336:26)
    at tryCatcher (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Kenn\Pictures\yuanshan\kennx.github.io\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
`

**Comment by HeskeyBaozi** [comment]
`pages`生成失败，能否看一下你的文章markdown文件所在的目录结构，即`source`文件夹

**Comment by kennx** [comment]
![tim 20180426184747](https://user-images.githubusercontent.com/1140099/39301656-752ab13a-4982-11e8-9af1-9de3e0918c92.png)
@HeskeyBaozi

**Comment by HeskeyBaozi** [comment]
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.4.4"
  },
  "dependencies": {
    "hexo": "^3.4.3",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-generator-to-json": "^1.1.12",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```
这是我可以用的`package.json`文件，你的报错信息我个人认为是`hexo`没有取到对应的页面信息`pages`。我本地也没办法复现你出现的错误。
